name: Deploye Next.js Application

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env && echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
      - name: Build docker image
        run: docker build -t test043/promage .
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        run: docker push test043/promage:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Stop Existing Container
        run: docker stop promage-container || true
      - name: Delete Existing Container
        run: docker rm -f promage-container || true
      - name: Pull Image from Docker Hub
        run: docker pull test043/promage:latest
      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name promage-container test043/promage
